language: node_js

install: npm ci

before_script: 
  - npm run lint
  - npm run build

script: npm run test:ci

deploy:
  skip_cleanup: true
  provider: script
  script: npm run release
  on:
    branch: master
